### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by charleston10** [cheeriojs/cheerio-select#25]
I didn't understand how to initialize

**Comment by fb55** [comment]
I agree that the documentation isn't good. For now, have a look at the `css-select` docs, as this module is just an extension of `css-select`.

**Comment by mikemajara** [comment]
Can you link the `css-select` docs or point somewhere where users can understand where to go?

**Comment by fb55** [comment]
This is a good starting point: https://github.com/fb55/css-select/blob/master/README.md

**Comment by fb55** [comment]
I am happy with the README as it is now.
