### ISSUE TITLE
syntax error in index.d.ts file.

### ISSUE THREAD

**Issue by dawoodEsketchers97** [cheeriojs/cheerio-select#348]
Hi Guys,
I am getting the following error when compiling the my typescript project (which uses cheerio and cheerio-select). Can someone help me with this error. Thanks!

**node_modules/cheerio-select/lib/index.d.ts:1:15 - error TS1005: ',' expected.
1 import { type Options as CSSSelectOptions } from "css-select";
Found 1 error.**

**I am using**
Node v14.18.0 
npm 8.1.3
cheerio ^1.0.0-rc.12
cheerio-select ^2.1.0

**Following are my ts confings**

{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "inlineSourceMap": true,
        "inlineSources":true,
        "removeComments": true,
        "outDir": "dist",
        "baseUrl": ".",
        "resolveJsonModule":true,
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "include": [
        "src/**/*"
    ]
}

**Comment by fb55** [comment]
What TypeScript version are you using?

**Comment by dawoodEsketchers97** [comment]
> 

Currently the project is using 4.2.4

**Comment by ff-taylor-dickinson** [comment]
node_modules/cheerio-select/lib/index.d.ts:1:15 - error TS1005: ',' expected.

1 import { type Options as CSSSelectOptions } from "css-select";
                ~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:4:27 - error TS1005: ',' expected.

4 export { DomHandler, type DomHandlerOptions };
                            ~~~~~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:32:37 - error TS1005: ',' expected.

32 export { default as Tokenizer, type Callbacks as TokenizerCallbacks, } from "./Tokenizer.js";

**Comment by ff-taylor-dickinson** [comment]
node_modules/cheerio-select/lib/index.d.ts:1:15 - error TS1005: ',' expected.

1 import { type Options as CSSSelectOptions } from "css-select";
                ~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:4:27 - error TS1005: ',' expected.

4 export { DomHandler, type DomHandlerOptions };
                            ~~~~~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:32:37 - error TS1005: ',' expected.

32 export { default as Tokenizer, type Callbacks as TokenizerCallbacks, } from "./Tokenizer.js";
                                       ~~~~~~~~~

**Comment by ff-taylor-dickinson** [comment]
This occurs just installing latest cheerio with latest typescript

**Comment by ff-taylor-dickinson** [comment]
{
  "name": "cheeriotypescripttest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cheerio": "^1.0.0-rc.12",
    "typescript": "^4.7.4"
  }
}

**Comment by ff-taylor-dickinson** [comment]
"target": "es6",
    "lib": [
      "es5",
      "es6",
      "dom",
      "scripthost",
      "es2016",
      "es2017",
      "es2020"
    ]

**Comment by ff-taylor-dickinson** [comment]
I had the same issue. Then I upgraded my global typescript and it fixed the issue.

npm -g upgrade typescript

**Comment by fb55** [comment]
See https://github.com/cheeriojs/cheerio/issues/2545#issuecomment-1183477852

**Comment by mccxiv** [comment]
Welp, running into these still.

```
../../node_modules/cheerio-select/lib/index.d.ts:1:15 - error TS1005: ',' expected.

1 import { type Options as CSSSelectOptions } from "css-select";
                ~~~~~~~

../../node_modules/cheerio/node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~

../../node_modules/cheerio/node_modules/htmlparser2/lib/index.d.ts:4:27 - error TS1005: ',' expected.

4 export { DomHandler, type DomHandlerOptions };
                            ~~~~~~~~~~~~~~~~~

../../node_modules/cheerio/node_modules/htmlparser2/lib/index.d.ts:32:37 - error TS1005: ',' expected.

32 export { default as Tokenizer, type Callbacks as TokenizerCallbacks, } from "./Tokenizer.js";
                                       ~~~~~~~~~


Found 4 errors.
```

tsconfig: 
```
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "allowJs": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
```

package.json
``` 
    "cheerio": "1.0.0-rc.12",
    "typescript": "4.9.4",
    "vite": "3.2.4",
    "vite-plugin-checker": "0.5.2",
    "vue-tsc": "1.0.13"
```

**Comment by fb55** [comment]
Have a look at my answer above

**Comment by rolandsfr** [comment]
did the issue get resolved? I'm experiencing the same problem

**Comment by fb55** [comment]
The root cause is an old TypeScript version, which does not support `import { type Foo } from '...'`. Upgrading TypeScript should do the job.

**Comment by mccxiv** [comment]
> The root cause is an old TypeScript version, which does not support `import { type Foo } from '...'`. Upgrading TypeScript should do the job.

You were right. I was accidentally using an old version of TS from the root of my monorepo. All good now
