### ISSUE TITLE
Wrong types generated

### ISSUE THREAD

**Issue by sl45sms** [cheeriojs/cheerio-select#436]
The types generated from this import is wrong

`import { type Options as CSSSelectOptions } from "css-select";`
https://github.com/cheeriojs/cheerio-select/blob/b7ffeebd211840309ffab57128685a0073a59d8c/src/index.ts#L2
Should be 
`import type { Options as CSSSelectOptions } from "css-select";`

so, the import may be rewritten as
```
import type {  Options as CSSSelectOptions }  from "css-select";
import { _compileToken as compileToken,
              prepareContext
} from "css-select";
```

**Comment by fb55** [comment]
My hunch is that you are on an old TypeScript version — this is valid syntax as written. If upgrading TypeScript doesn't fix things, please provide some more details on what you are trying to accomplish.

**Comment by sl45sms** [comment]
My bad, yes, you are absolutely right. :( 
Yes it is a valid syntax.
