### ISSUE TITLE
Cheerio-select version 1.0.0 issue with grunt-dom-munger

### ISSUE THREAD

**Issue by amkoba** [cheeriojs/cheerio-select#5]
Getting below error while running "dom_munger:read" (dom_munger) task

**Processing index.html
Warning: select is not a function Use --force to continue.**

Version 
**"cheerio-select": "1.0.0"** 

Newer version is using css-select instead of CSSselect dependency package.

**Comment by fb55** [comment]
My guess is that you will have to pin `cheerio-select` to `< 1.0.0`, as this grunt task seems to be using a very old version of Cheerio. If that doesn't work, please post code to replicate the issue.

**Comment by amkoba** [comment]
@fb55, Yes, that worked. 
What is the issue with 1.0.0. version ?

**Comment by fb55** [comment]
1.0.0 doesn't have the same exports as the old versions. That leads to the error you are seeing.

It seems like the old cheerio version is using an overly permissive range, leading to this issue. Versions this old aren't supported anymore, so please consider upgrading Cheerio to solve this.
